"use client";
// import type { Metadata } from "next";
import { spaceGrotesk } from "./fonts";
import NavBar from "./ui/navbar/navbar";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import { useState } from "react";

// export const metadata: Metadata = {
//   title: "CyptoSphere",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [isDark, setIsDark] = useState(true);

  return (
    <html lang="en">
      <StoreProvider>
        <body
          className={`${
            spaceGrotesk.className
          } antialiased transition-bg ease-in-out ${
            isDark ? "bg-[#13121A]" : "bg-white"
          }`}
        >
          <NavBar changeTheme={(value: boolean) => setIsDark(value)} />
          {children}
        </body>
      </StoreProvider>
    </html>
  );
}
